# применение конфигурации kube-prometheus и деплой nginx только при коммитах в ветку main.
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm install kube-prometheus prometheus-community/kube-prometheus-stack -f kube-prom.yaml
    - kubectl apply -f deployment.yaml
  only:
    - main

